### ISSUE TITLE
Why no duplicates?

### ISSUE THREAD

**Issue by smonasco** [nomemory/mapneat#2]
I'm looking for json to json transformers for a translation layer between different schemas, one of which I do not own. Obviously a good use case for your library which looks awesome :)

In general, duplicates are annoying, and if I'm merging from multiple sources into the same target it's possible it'll create a bug. However, JSON allows for duplicates and if there are duplicates in the source I should certainly honor that.

I'm struggling to come up with a well formed schema that leads to such, but I can think of real world examples of less than pretty data.

Sometimes you run into associated arrays

{
  "ratings_providers": [ "a", "b", "c" ],
  "ratings": [ 5, 5, 4.5 ]
}

Not my favorite but I've seen it and I may have to merge into it. I'm not sure what other cases I might have. It may be best if I run into them and then bring them back but if they are in the source that might cause a production bug...

Thoughts? Could we turn it on or off as optional parameters to the json object constructor?

**Comment by nomemory** [comment]
Hello,

Thanks for stopping by.

I am not sure how easy is to implement duplicates support. 

Internally mapneat uses jsonpath, and jsonpath uses jackson. 

Jackson doesn't like duplicates, so it either fails by throwing an exception or the behavior is random and if a key is duplicated the value jackson retrieves is either one of the two possibilities. I need to double-check.

I can't think out of my head of any solution for this, other than modifying the jsonpath library to use another possible JSON provider.

In case you suspect the source has duplicates, and of course the source is out of your control (e.g.: legacy system), you need to sanitise the json programatically before using it in mapneat. This is my suggestion.

Andrei
