### ISSUE TITLE
Question on copying entire source JSON

### ISSUE THREAD

**Issue by dalegaspi** [nomemory/mapneat#3]
hello!

i am currently evaluating this library for transformation and kindly excuse me for this embarrassingly stupid question: how do you you copy the entire original JSON from src to target?  the use case that i have is that i want to copy the entire doc but just add a few fields.

the example input:
```json
{
  "hello": "world"
}
```
and this transformation:
```kotlin
fun copySourceDoc(input: String): String {
  return json(input) {
    "." *= "$"
   // ... do other transformation stuff here
  }.getPrettyString()
}
```

results in:
```json
{
  "" : {
    "" : {
      "hello" : "world"
    }
  }
}
```

i mean, i would assume that there is some flag/parameter that you can use to copy the source by default so i don't even have to explicitly copy it?

**Comment by nomemory** [comment]
To be absolutely honest this is something missing from the library. I've realised I am missing this after finishing the first draft implementation.

 I will need to add two things:
- just like you said, a flag to automatically copy the source;
- support for $root on the left side notation 

Sorry for this inconvenience.

**Comment by dalegaspi** [comment]
@nomemory thank you for the response.  right now, obviously there's way to get around this, so i wouldn't say it's a dealbreaker...nevertheless, i am looking forward to seeing this feature implemented. 😊

**Comment by nomemory** [comment]
@dalegaspi 

To support this was an easy task, easier than I expected, so it's done in version `0.9.3`. 

You can use `"" *= "$"` or call the method: `copySourceToTarget()` directly in the transformation.

Additionally you can also merge a JSON object from the target into the target if you use something like this: `"person." *= <jsonpath returning a Map<,>`.

Hope it's helpful.

**Comment by dalegaspi** [comment]
@nomemory yep...works like charm!  you can close this issue now.  thanks!
